### ISSUE TITLE
`jobStatusMap` inside `_graphvizDot()` not initialized

### ISSUE THREAD

**Issue by pb-jchin** [PacificBiosciences/pypeFLOW#16]
`jobStatusMap` was an instance variable in `controller.py`.  The recent refactoring make is a local variable inside `_refreshTargets()`.   The local variable `jobStatusMap` inside `_graphvizDot()` needs initialization now.   This is a minor issue. I only use `_graphvizDot()` for some debugging processes.

**Comment by pb-cdunn** [comment]
Reverted to instance-variable.
