### ISSUE TITLE
Create multi-threaded, blocking process-watcher

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pypeFLOW#31]
Given a string like one of these (from PacificBiosciences/FALCON-pbsmrtpipe#31):

* `qsub -S /bin/bash -sync y -V -q production -N ${JOB_ID} \\\n    -o "${STDOUT_FILE}" \\\n    -e "${STDERR_FILE}" \\\n    -pe smp ${NPROC} \\\n    "${CMD}"`
* `runjmscmd ... (same variables)`
* `bash "${CMD}" > ${STDOUT_FILE} 2> ${STDERR_FILE}`

We need a process-watcher which uses a thread per job. Each thread will block on the qsub call.

We need to ensure that the calls are killed and the whole pwatcher is killed when the main program dies.

- Submit
  - [x] Start a thread for each job.
  - [x] When a thread dies, it must update the State using a Lock.  Or it must use a queue or notification.
- Query
  - [x] With a lock, examine the current State.
- Delete
  - [x] Kill all on any exit, including Ctrl-C.

These will wait for another day:

- Delete
  - Kill the corresponding running thread and (with a lock) update the State, carefully.
  - Kill all on any exit, including Ctrl-C.
- Restart
  - Upon restart, ensure that finished tasks are not re-run, even if they failed before.

**Comment by mhsieh** [comment]
one idea is to just use multiprocessing.Pool()
```
someList=[1,2,3,4]
pool = multiprocessing.Pool(ncores)
result=pool.map_async(someFunc,somList).get(9999999)
```
`.get(999999)` seems to have a side effect that makes Ctrl-C works :D

**Comment by pb-cdunn** [comment]
Progress is on the `blocking` branch:
* https://github.com/PacificBiosciences/pypeFLOW/blob/blocking/pwatcher/blocking.py

**Comment by pb-cdunn** [comment]
MJ, the `multiprocessing` module is usually unwise, for a variety of reasons. I used to like it, but I've learned. There are very few cases when it is actually a good solution, except for something quick-and-dirty. I don't have time to give you the full lecture right now.

In my Python implementation last night, I used a thread per call. That's not ideal, but I think it's ok since we already limit concurrency from the workflow side. (Different FALCON stages have different `max_concurrency`.)

(In my opinion, GoLang is a much better choice than Python for this, since each blocking call could be in its own goroutine, which is cheap. The caveats are suddenly far fewer. But this is a tiny amount of code, only a few hundred lines, so we can re-write in a couple hours down the road.)

The main problem I have with my current version is that termination is a bit tricky. We could share a repo with my little test-case, and you could experiment with different cases if you want. Ctrl-C at least seems to do the right thing, though I haven't tried it yet with a real qsub job.

The other difficulty is that this blocking "pwatcher" is *ipso facto* not actually restartable. So it's not really "watching" anything. That's fine, but we have to change slightly how this thing is called. Two choices:

1. Currently, the `fs_based.py` pwatcher is in-process with FALCON. If we want `blocking.py` also in-process, then we need to stop using the `process_watcher` context-manager repeatedly (or we would need global state).
2. Alternatively, `blocking.py` could be run as a separate process, either using IPC or using repeated socket reconnections. But then we have to consider how to kill it.

I was going to start working on (1) next, but if you really want to work with me on this, let's discuss in Slack. I move pretty quickly, but I don't mind working super-closely with you if you're up for it. I've done several weekend-long programming contests -- where a team of devs works *very* closely without much sleep for 72 hours -- so I know how to move fast as part of a team. We have a Friday morning deadline (unless this requirement is officially dropped from Goat, as Paul suggested in bugzilla).

On the other hand, if you'd rather work independently, I have an idea for you. Let's discuss in Slack.
