### ISSUE TITLE
Problem with network_based pwatcher on OSX

### ISSUE THREAD

**Issue by cdunn2001** [PacificBiosciences/pypeFLOW#37]
```py
Traceback (most recent call last):
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/fc_env/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 668, in main
    main1(argv[0], args.config, args.logger)
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 432, in main1
    watcher_directory=config['pwatcher_directory'])
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py", line 553, in PypeProcWatcherWorkflow
    watcher = pwatcher_impl.get_process_watcher(watcher_directory)
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/pypeFLOW/pwatcher/network_based.py", line 905, in get_process_watcher
    state = get_state(directory)
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/pypeFLOW/pwatcher/network_based.py", line 402, in get_state
    watcher_state.initialize(directory, hostname, port)
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/pypeFLOW/pwatcher/network_based.py", line 373, in initialize
    self.top['auth'], self.top['server'] = start_server(self.get_server_directories(), hostname, port)
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/pypeFLOW/pwatcher/network_based.py", line 238, in start_server
    hostname = get_localhost_ipaddress(hostname, port)
  File "/Users/cdunn2001/repo/gh/FALCON-integrate/pypeFLOW/pwatcher/network_based.py", line 193, in get_localhost_ipaddress
    list = socket.getaddrinfo(socket.gethostname(), port, socket.AF_INET, socket.SOCK_STREAM)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
Completely outside pypeflow:
```py
>>> import socket
>>> socket.gethostname()
'MacBook-Air.local'
>>> port = 0
>>> socket.getaddrinfo(socket.gethostname(), port, socket.AF_INET, socket.SOCK_STREAM)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by mhsieh** [comment]
I guess we need to work on the case when hostname is a zeroconf hostname.

**Comment by mhsieh** [comment]
Actually I can't reproduce it.
```
$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostname()
'mini.local'
>>> socket.getaddrinfo(socket.gethostname(), 0, socket.AF_INET, socket.SOCK_STREAM)
[(2, 1, 6, '', ('172.16.1.5', 0))]
>>> 
```

**Comment by pb-cdunn** [comment]
Hmm. Odd. But I read something a few days ago about having to open ports after upgrading to Sierra, though I couldn't find any bad settings. `'localhost'` and `'127.0.0.1'` both work fine.

**Comment by pb-cdunn** [comment]
MJ, what is in your `/etc/hosts` file? My does not have `'MacBook-Air.local'`. Could that be the problem?

**Comment by mhsieh** [comment]
```
mjhsieh:~ mjhsieh$ grep '\.local' /etc/hosts
mjhsieh:~ mjhsieh$ python -c 'import socket;print socket.gethostname()'
mjhsieh.local
mjhsieh:~ mjhsieh$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555
```

**Comment by mhsieh** [comment]
perhaps `socket.getfqdn()` is better (?)

**Comment by pb-cdunn** [comment]
```py
>>> socket.getfqdn()
'MacBook-Air.local`
```
Same result, and it takes several seconds. However, if I put `MacBook-Air.local` into `/etc/hosts`, then fqdn returns `1.0.0.127.in-addr.arpa`.

**Comment by pb-cdunn** [comment]
```sh
$ scutil --get LocalHostName
MacBook-Air
```
I'm stumped. I guess we can put the current code into a try-block and fallback to `localhost`. But if you have some idea how to fix my Mac, please tell me.

**Comment by pb-cdunn** [comment]
When I add a try-block, it runs, but it's really really slow. I suspect that function is called many times, which is not good, but I'm not sure since I do not see my new log message anywhere.

For reference, the `blocking` pwatcher with `job_type=local` and `job_queue=bash -C ${CMD}` takes about 20secs; `fs_based` take 3mins; `network_based` now takes even longer.

**Comment by mhsieh** [comment]
```
iMacCD:~ mjhsieh$ python -c 'import socket;print socket.getaddrinfo(socket.gethostname(), 0, socket.AF_INET, socket.SOCK_STREAM)'
[(2, 1, 6, '', ('10.0.1.11', 0))]
iMacCD:~ mjhsieh$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.6.8
BuildVersion:	10K549
```

**Comment by mhsieh** [comment]
Chris, are you using a clean-installed macosSierra?

**Comment by cdunn2001** [comment]
It's an upgrade. Very strange, since it works fine for `localhost`. You'd think it would be an easy matter to figure out how to make OSX see `MacBook-Air.local` as `127.0.0.1`, but I have not figured it out. Web-searches show how to fix it when *nothing* works, including `localhost`.

**Comment by cdunn2001** [comment]
Btw, I finally found the reason for the slow-down of `fs_based` on the Mac. This line is slow:

    hostname = socket.getfqdn()

In `fs_based`, that is purely informational, and it takes a few seconds on my Mac. I'll remove it.

I think the slow-down in `network_based` is mostly from waiting on read/write buffers for logging. But if `getaddrinfo()` is called repeatedly, that could be the cause instead. We need to try logging direct to disk.

**Comment by mjhsieh** [comment]
Which python are you using?

**Comment by mjhsieh** [comment]
And see if you can ping MacBook-Air.local :D

**Comment by cdunn2001** [comment]
```sh
$ which python
/usr/local/bin/python
$ greadlink -f $(which python)
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
$ ping MacBook-Air.local
ping: cannot resolve MacBook-Air.local: Unknown host
$ ping localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.126 ms
```
So how do I make the 'hostname' pingable?

**Comment by cdunn2001** [comment]
By adding `127.0.0.1       MacBook-Air.local` into `/etc/hosts`, I got **ping** working. But `getaddrinfo()` still does not work (except for `localhost` or `127.0.0.1`).

**Comment by mjhsieh** [comment]
What if you use /usr/bin/python ? I will test this without logging into wifi/ethernet ...

**Comment by mjhsieh** [comment]
Now this look interesting after I logged off network
```
Last login: Fri Nov  4 20:51:20 on ttys006
mengjueh:~ mjhsieh$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostname()
'mengjueh.local'
>>> socket.getaddrinfo(socket.gethostname(),0,socket.AF_INET,socket.SOCK_STREAM) 
[(2, 1, 6, '', ('127.0.0.1', 0))]
>>> ^D
mengjueh:~ mjhsieh$ ping mengjueh.local
PING mengjueh.local (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.042 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.091 ms
^C
--- mengjueh.local ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.042/0.067/0.091/0.024 ms
```

**Comment by mjhsieh** [comment]
So how did you set your hostname ? I only did set it up in System Preferences... -> Computer Name: -> mengjueh

**Comment by cdunn2001** [comment]
`/usr/bin/python` is `2.10.0`, but the result is the same.

... Well, I got it working. I added `.local` into "DNS Search Domains". I tried that yesterday, but that was before I also updated `HostName` with `scutil` (in the other Issue). So this Issue is closed, but the speed problem remains.
