### ISSUE TITLE
Bad argument to sbatch with SLURM

### ISSUE THREAD

**Issue by bredelings** [PacificBiosciences/pypeFLOW#40]
After installing falcon through FALCON-integrate and successfully running 'make test', I tried to run the same test with SLURM.  This failed, but the log showed that a bad "-q arg" argument was being supplied to sbatch.

I was able to get synth0 to run to completion by removing this argument from the 'sge_cmd' in pwatcher/fs_based.py and pwatcher/network_based.py .  However, I think that (assuming SLURM 'partitions' are analogous to SGE 'queues') the "-q" should just be changed to "-p" for sbatch.

See also readme.slurm.md, which has a "-p" option, but not a "-q" option.

**Comment by bredelings** [comment]
[fix_queue.txt](https://github.com/PacificBiosciences/pypeFLOW/files/609622/fix_queue.txt)

**Comment by pb-cdunn** [comment]
Were you the one communicating with us privately?

If you submit a PR, I'll merge it immediatley. Otherwise, we'll get to this in a couple of days.

**Comment by bredelings** [comment]
No, that must be someone else.  I created a PR, thanks for helping.

**Comment by bredelings** [comment]
Another alternative would simply be to delete all the "-q {queue_name}" and "-p {queue_name}" options.  This would allow users to specify the queue themselves:

job_queue = debug
sge_option_da = -c5 --mem=10g -p %(job_queue)s

It would also allow the users to not specify the queue.  At least on SLURM, the default queue is then used.  The downside is that people's previously-written fc_run.cfg files might stop working if they specify a queue via the job_queue variable, but don't put it in the sge_option's explicitly.

**Comment by hans-vg** [comment]
Thank you!  I ran into this problem on Friday last week but haven't had a chance to dig into the code to fix it.  I'll test your changes and see if it fixes the SLURM problem on our local cluster.

pb-cdunn - I was the one communicating with you and Jason.

**Comment by hans-vg** [comment]
Since I already had the sge_option_da = -p %(jobqueue)s syntax in my configuration file, I was having -p set twice during submission after implementing your bugfix in the second post.

I opted for removing the -p/-q option from the `sge_cmd` on these SLURM specific methods.  This way I can have the sge_option_* values in the cfg file individually set the partition types when submitting the job.

**Comment by pb-cdunn** [comment]
The reason for adding `-q {queue_name}` was for compatibility with an internal workflow. We no longer need that, so I will try to change this to use job_queue only if provided.

**Comment by pb-cdunn** [comment]
Fixed by @bredelings in #42.
