### ISSUE TITLE
newly created directories not always available fro remote job

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/pypeFLOW#49]
This is similar to an earlier issue I commented  on, and still appears to be an issue.  The wrapper script created by simple_pwatcher_bridge.py tries to cd {wdir}, and it fails because that directory hasn't yet propogated from the program's head node to the remote node the job is run on.  This one has a very simple fix:

--- simple_pwatcher_bridge.py      2017-05-31 10:57:47.317485000 -0500
+++ simple_pwatcher_bridge.py   2017-05-31 10:58:59.469657000 -0500
@@ -350,6 +350,7 @@
         rel_actual_script_fn = os.path.relpath(actual_script_fn, wdir)
         wrapper = """#!/bin/sh
 set -vex
+mkdir -p {wdir}
 cd {wdir}
 bash {rel_actual_script_fn}
 touch {sentinel_done_fn}

mkdir -p will return success if the directory already exists, and the attempt to create the directory forces it to propogate to the node the job is running on.

**Comment by pb-cdunn** [comment]
The wrappers (which run from the installation, not from the remote directory) should now cause the remote job to wait for all known input files to become available.
