### ISSUE TITLE
add support for SLURM job dependencies to pypeFLOW

### ISSUE THREAD

**Issue by aclum** [PacificBiosciences/pypeFLOW#50]
checking on jobs in a tight look is hard on our scheduler.  Is there a way to control the frequency or better yet add support to use SLURM job dependencies?

**Comment by pb-cdunn** [comment]
> checking on jobs in a tight look is hard on our scheduler.

Could you explain? I don't understand what is "checking on jobs".

You can reduce the concurrency (`njobs` in latest release) if there are too many simultaneous jobs. And if the file-system based checking is the problem, you can switch to the `blocking` pwatcher. See both FALCON and pypeFLOW wikis for "Configuration". (The network-based process-watcher is currently broken, but it could be resurrected quickly.)

> add support to use SLURM job dependencies?

**Comment by aclum** [comment]
We are primarily having trouble getting out jobs to schedule since falcon submits so many small jobs. We'd like support so that for example the 2-asm-falcon jobs were queued earlier but dependent on preassembly daligner jobs to complete. 

sbatch --dependency=afterok:11254323 task.sh

where task.sh is the 2-asm-falcon job and 11254323 is a queued daligner job.

**Comment by pb-cdunn** [comment]
> We are primarily having trouble getting out jobs to schedule since falcon submits so many small jobs.

If the problem is too many *simultaneous* jobs, simply set `*_concurrent_jobs=small_number`.

Or with the latest code:
```ini
[job.defaults]
njobs = small_number
```

> We'd like support so that for example the 2-asm-falcon jobs were queued earlier but dependent on preassembly daligner jobs to complete.

pypeflow does in fact queue up as many jobs as the workflow graph allows. Limited by `njobs` (or the legacy "concurrent_jobs"). However, because the graph is not entire knowable in advanced -- the number of parallel tasks is dynamic -- we have several synchronization points where we wait for a previous task to complete before we can fill out the graph further.

Maybe if you post your cfg I could understand your problem better.

**Comment by aclum** [comment]
Our problem is with priority shares on our cluster and long times waiting
in the queue as many groups and users share the same resource. To work
around it we've currently switched to running locally so the entire job
just runs on a single node but jobs would get higher priority if all the
jobs could be scheduled all at once even if they can't run yet b/c upstream
tasks haven't finished. It sounds like based on your last comment though
that this isn't possible based on the workflow graph. Is that correct?

**Comment by pb-cdunn** [comment]
> jobs would get higher priority if all the
jobs could be scheduled all at once even if they can't run yet b/c upstream
tasks haven't finished. It sounds like based on your last comment though
that this isn't possible based on the workflow graph. Is that correct?

Correct. And that's a general problem. But you can set `njobs=large_number` (i.e. high number of concurrent_jobs). That would be especially helpful to you for Daligner. Pypeflow's filesystem-based process-watcher (`fs_based`, the default `pwatcher_type`) can handle thousands easily; you'll have that many threads, but that should be fine.

Are you saying that you need a way to submit thousands of jobs on a single command-line? If so, that's interesting, but no, we don't currently support that. If you own a Sequel machine and need that feature, please contact marketing. It's possible, but a complex feature like that would require a strong business case.

There is also a `squash` parameter to combine sequential tasks into one. That could you help for the non-parallel jobs. Unfortunately, it is not currently exposed. But you can hack it: Set `length_cutoff` explicitly (i.e. not `-1`), and set `genome_size=1`. The should cause `squash=True` in `run1.py`.

Beyond that, there's not much we can do for you.
