### ISSUE TITLE
No git tags for each version

### ISSUE THREAD

**Issue by peterjc** [PacificBiosciences/pypeFLOW#51]
Looking at setup.py the current version is 2.0.2, and the history would let us track back and find specific version bumps - for example https://github.com/PacificBiosciences/pypeFLOW/commit/cefc4ac03418e60200ce68aff05c49d3e54cd36e#diff-2eeaed663bd0d25b7e608891384b7298 jumped from 1.1.0 to 2.0.0

However, without explicit tags, it hard to be sure that commit itself represented the 2.0.0 release, or if it was a slightly later commit.

**Comment by peterjc** [comment]
Only one version tag exists right now,

* v0.1.0 - https://github.com/PacificBiosciences/pypeFLOW/tree/v0.1.0

Missing entries:

* v0.1.1 - https://github.com/PacificBiosciences/pypeFLOW/commit/ff635f4605baac5f66cb000e552ddb3dcf98d34a#diff-2eeaed663bd0d25b7e608891384b7298
* v1.0.0 - https://github.com/PacificBiosciences/pypeFLOW/commit/79c77235eb10e7b36a98ada891e1e6ef454aed58#diff-2eeaed663bd0d25b7e608891384b7298
* v1.1.0 - https://github.com/PacificBiosciences/pypeFLOW/commit/67d1b7216116c782e9935912dc20764fd3174bfa#diff-2eeaed663bd0d25b7e608891384b7298
* v2.0.0 - https://github.com/PacificBiosciences/pypeFLOW/commit/cefc4ac03418e60200ce68aff05c49d3e54cd36e#diff-2eeaed663bd0d25b7e608891384b7298
* v2.0.1 - https://github.com/PacificBiosciences/pypeFLOW/commit/78c975bf53263797da4c6edeec913713a1367b73#diff-2eeaed663bd0d25b7e608891384b7298
* v2.0.2 - https://github.com/PacificBiosciences/pypeFLOW/commit/374533b1dc9eee960b18c88f9395b3f3af5fef1e#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by pb-cdunn** [comment]
I don't know who set up the pypeflow Bioconda recipe. We plan to deploy all of Falcon to Bioconda fairly soon, but we are not supporting what's there yet.

**Comment by peterjc** [comment]
The vast majority of BioConda recipes are created and maintained without help from the package authors, although your input is of course welcome. BioConda already has Falcon, all be it an older version. Part of the trouble here is that the PacBio repositories have not taken full advantage of git in their release process, making it harder than it should be to pull out a specific release from the commit history.

However, this is wider issue than just BioConda packaging, it affect all packing efforts such as Linux distributions or homebrew. Also, this is an impediment to reproducible science as installing specific versions can be important for retracing past analyses.

Please consider re-opening this issue, and adding release tags to this git repository.
