### ISSUE TITLE
qsub jobs submission error

### ISSUE THREAD

**Issue by wuxiaopei0509** [PacificBiosciences/pypeFLOW#55]
I have another problem with job submission.the job submission section is as follows:
and my submit command is：
qsub -S /bin/bash -sync y -V \
-q all.q \
-N Assemble \
-o Assembleoutput \
-e AssembleSTDERR \
-pe smp 10 \
-l h_vmem=1000M \
/home/wuxiaopei/miniconda2/bin/fc_run.py /data/wuxiaopei/fc_run.cfg
Immediately，the  error occurs :
![图片](https://user-images.githubusercontent.com/52643750/62761460-4a503f80-bab9-11e9-8814-8ed374415784.png)

I don't know how to do with it.Can you tell me ?Thank you very much``

**Comment by pb-cdunn** [comment]
You might need to submit "python" as the executable and `fc_run.py fc_run.cfg` as the arguments. It seems to be trying to execute `fc_run.py` as a bash program.
